# Automatically generated by ydf
{% if ydf is defined %}
    {% for key, value in ydf.items() -%}
        # {{ key.capitalize() }}: {{ value }}
    {% endfor %}
{% endif %}
# ---
{% if meta is defined %}
    {% for key, value in meta.items() -%}
        # {{ key.capitalize() }}: {{ value }}
    {% endfor %}
{% endif %}
# ---

{% if instructions is defined %}
  {% for instruction in instructions -%}
      {{ convert_instruction(instruction) }}

  {% endfor %}
{% endif %}
