# Automatically generated by ydf
{% if ydf %}
    {% for key, value in ydf.items() -%}
        # {{ key.capitalize() }}: {{ value }}
    {% endfor %}
{% endif %}
# ---
{% if meta %}
    {% for key, value in meta.items() -%}
        # {{ key.capitalize() }}: {{ value }}
    {% endfor %}
{% endif %}
# ---

{% for instruction in instructions -%}
    {{ to_docker_instruction(instruction) }}
{% endfor %}
